# Generated by Django 4.1.6 on 2023-04-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0002_studentmodel_beautiful_alter_studentmodel_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='beautiful',
            field=models.CharField(max_length=3),
        ),
    ]
