# Generated by Django 4.1.6 on 2023-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0003_alter_studentmodel_beautiful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='feedback',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='suggested',
            field=models.CharField(default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='useful',
            field=models.CharField(default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='working',
            field=models.CharField(default='yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='beautiful',
            field=models.CharField(default='yes', max_length=3),
        ),
    ]
