# Generated by Django 4.1.6 on 2023-04-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0004_remove_studentmodel_feedback_studentmodel_suggested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='beautiful',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='suggested',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='useful',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='working',
            field=models.CharField(max_length=100),
        ),
    ]
